repos:
  - repo: https://github.com/astral-sh/ruff-pre-commit
    rev: v0.15.9
    hooks:
    - id: ruff
      args: ["--fix"]  # auto-fix import order
    - id: ruff-format
  
  - repo: https://github.com/codespell-project/codespell
    # Configuration for codespell is in pyproject.toml
    rev: v2.4.3
    hooks:
    - id: codespell
